// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tplibrary

var TableNames = struct {
	MaterialTypes string
	Materials     string
}{
	MaterialTypes: "material_types",
	Materials:     "materials",
}
